### ISSUE TITLE
[US-6-8][Medium] Page scroll leads to several locators deleting

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#228] opened 2022-01-27 11:57 UTC
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome, MacOS
https://jdi-family.atlassian.net/wiki/home

1) open page from precondition
2) open JDN browser console tab
3) empty cache and hard reload for the the page
4) identfy
5) wait for locators list appearance 
6) scroll the page quickly before identifying ends

AR: some locators move to the deleted group
ER: locators can be deleted only by users activity like delete button clicking not scroll

**Comment by savinovava** [comment] 2022-02-01 07:04
It will be fixed with #171

**Comment by AlexeyGirin** [comment] 2022-02-03 07:48
Not a bug

**Closed by AlexeyGirin** 2022-02-03 07:48 UTC
Labels: bug
